### PR TITLE
Unit test Github Action

### PR DESCRIPTION
**Pull request by DanFerrer**
#### What does this PR do?
-  Adds Github Action to run unit tests when a new PR is made to development or master

#### Description of Task to be completed?
- n/a

#### How should this be manually tested?
- Create a new pull request when this merged
- Click on the actions tab to view the unit test workflow (I'll make a dummy PR after this is merged to test it

#### What are the relevant Trello Card stories? [ Trello Card Item ](https://trello.com/b/8x3mo2V5/say-their-names-web)
- https://trello.com/c/G6DVclL0/107-add-github-action-to-run-tests

#### Pull Request Type (check one)
- [ ] Feature
- [ ] Bug Fixes
- [x] Chore

#### Developer Checklist
- [x] New code has been scanned for ESlint issues
- [x] I have tested my code locally
- [x] I made sure that there are no other pull requests that solve for this issue
- [x] My code follows the same structure within the guidelines

#### Screenshots (if appropriate)
Created a dummy pr on my fork to test it:
Screen Shot 2020-06-08 at 12 37 18 PM

### CODE REVIEW

**Comment by DanFerrer** [comment]
@Easybuoy Do we have a minimum node version for this project? I set up the action to run on node version 12

**Comment by Easybuoy** [comment]
> @Easybuoy Do we have a minimum node version for this project? I set up the action to run on node version 12

Yeah version 12's good

**Comment by Easybuoy** [comment]
Is it until it's merged before the Github action kicks in?

**Comment by TheDoctorCam** [comment]
@Easybuoy It _should_ work on this PR. I am taking a look now.

**Comment by DanFerrer** [comment]
It might not work in this PR because I'm developing on a fork, don't know if that matters:

Here it is working when i opened up a PR against my forks development branch: https://github.com/DanFerrer/say-their-names-web/pull/1/checks?check_run_id=750747562

**Comment by TheDoctorCam** [comment]
This plugin is great for running Github actions locally -- https://github.com/nektos/act

**Comment by TheDoctorCam** [comment]
But yes, I am thinking it is because of the fork because I am able to run it locally.

**Comment by TheDoctorCam** [comment]
It looks like using a fork to trigger github actions on pull requests is a known issue or a missing feature -- https://github.community/t/will-github-actions-support-pull-request-events-from-a-fork-to-a-private-base-repository/17471/2

**Comment by Easybuoy** [comment]
> It looks like using a fork to trigger github actions on pull requests is a known issue or a missing feature -- https://github.community/t/will-github-actions-support-pull-request-events-from-a-fork-to-a-private-base-repository/17471/2

We can just merge, it should work when merged then

**Pull request merged**
