### PR TITLE
Petitions page content

### PR DESCRIPTION
**Pull request by jdshaeffer**
#### What does this PR do?
- Add the cards and content for the petitions page
- Followed styles as seen in the Mobile MVP (https://www.figma.com/file/AUlfUejB2SVF8ZHSzxne7O/STN?node-id=938%3A759)

#### Description of Task to be completed?
- Fix flex alignment of the Find Out More button to be at the bottom - or should the whole card be clickable - eliminating the need for a button?
- Get real data
- Images/other content besides black background at top of card

#### How should this be manually tested?
- None yet

#### What are the relevant Trello Card stories? [ Trello Card Item ]
(https://trello.com/c/An6ydzbd/48-petition-page)

#### Pull Request Type (check one)
- [x] Feature
- [ ] Bug Fixes
- [ ] Chore

#### Developer Checklist
- [x] New code has been scanned for ESlint issues
- [x] I have tested my code locally
- [x] I made sure that there are no other pull requests that solve for this issue
- [x] My code follows the same structure within the guidelines

#### Screenshots (if appropriate)
Screen Shot 2020-06-03 at 11 40 02 PM

### CODE REVIEW

**Comment by jdshaeffer** [comment]
Ok, I'll check that out, thanks!

**Comment by iamcristos** [comment]
nice job @jdshaeffer can you also change the hover effect on the button to use the same effect as the 'back to profile' button so are styles stays consistent.

**Comment by jdshaeffer** [comment]
@Easybuoy can you review this? This also includes the donations page. I don't know why it's including a lot of past commits. Should be fine though.

**Comment by jdshaeffer** [comment]
Messed up branch history, new PR in #41

**Pull request closed without merging**
