### PR TITLE
implemented new footer design

### PR DESCRIPTION
**Pull request by iamcristos**
#### What does this PR do?
- redesigns the footer to fit new design 

#### Description of Task to be completed?
-

#### How should this be manually tested?
- npm start

#### What are the relevant Trello Card stories? [ Trello Card Item ](https://trello.com/b/8x3mo2V5/say-their-names-web)
-

#### Pull Request Type (check one)
- [ ] Feature
- [ ] Bug Fixes
- [ ] Chore

#### Developer Checklist
- [ ] New code has been scanned for ESlint issues
- [ ] I have tested my code locally
- [ ] I made sure that there are no other pull requests that solve for this issue
- [ ] My code follows the same structure within the guidelines

#### Screenshots (if appropriate)
Screenshot 2020-06-06 at 2 11 29 AM

### CODE REVIEW

**Comment by kouamendri** [comment]
Could you resolve the conflicts? @iamcristos

**Comment by ashleygraf101** [comment]
Can you change SAY THEIR NAME to SAY THEIR NAMES?

**Comment by ashleygraf101** [comment]
Could you change SAY THEIR NAME to SAY THEIR NAMES in Our Mission?

**Comment by kouamendri** [comment]
Could you update this branch so we can get it merged in?

Nice work!

**Pull request merged**
