### PR TITLE
Profile preview

### PR DESCRIPTION
**Pull request by Easybuoy**
#### What does this PR do?
- Profile preview

#### Description of Task to be completed?
- Create `Profile Preview` to be able to preview profiles on the home page.
- Make a `GET` request to `https://saytheirnames.dev/api/people` to get list of profiles

#### How should this be manually tested?
- https://deploy-preview-23--saytheirname.netlify.app

#### What are the relevant Trello Card stories? [ Trello Card Item ](https://trello.com/b/8x3mo2V5/say-their-names-web)
- https://trello.com/c/bHKl5cGT/45-person-preview-component

#### Pull Request Type (check one)
- [x] Feature
- [ ] Bug Fixes
- [ ] Chore

#### Developer Checklist
- [x] New code has been scanned for ESlint issues
- [x] I have tested my code locally
- [x] I made sure that there are no other pull requests that solve for this issue
- [x] My code follows the same structure within the guidelines

#### Screenshots (if appropriate)

Screenshot 2020-06-03 at 13 12 59

### CODE REVIEW

**Comment by kouamendri** [comment]
My notes:

There see to be a lot of padding on 1024px viewport. Can we aim to keep that at a 3 column grid? https://ibb.co/PC276Bd

The list is not aligned with the 'Get Involved' component.

**Comment by Easybuoy** [comment]
> My notes:
> 
> There see to be a lot of padding on 1024px viewport. Can we aim to keep that at a 3 column grid? https://ibb.co/PC276Bd
> 
> The list is not aligned with the 'Get Involved' component.

Done!

**Comment by kouamendri** [comment]
Looks good!

**Comment by jpouabou** [comment]
Looks good!

**Pull request merged**
