### PR TITLE
feat:add notFound page

### PR DESCRIPTION
**Pull request by mbayefaye**
#### What does this PR do?
-add the not Found Page

#### Description of Task to be completed?
-add the not found page

#### How should this be manually tested?
-

#### What are the relevant Trello Card stories? [ Trello Card Item ](https://trello.com/b/8x3mo2V5/say-their-names-web)
-

#### Pull Request Type (check one)
- [x]  Feature
- [ ] Bug Fixes
- [ ] Chore

#### Developer Checklist
- [x ] New code has been scanned for ESlint issues
- [x ] I have tested my code locally
- [ x] I made sure that there are no other pull requests that solve for this issue
- [x ] My code follows the same structure within the guidelines

#### Screenshots (if appropriate)
Screen Shot 2020-06-05 at 3 15 32 PM

### CODE REVIEW

**Comment by iamcristos** [comment]
nice job. can you connect the page to the route so it renders when users navigate to a route that doesn’t exist?

**Comment by mbayefaye** [comment]
thank you @iamcristos i just did it .

**Comment by kouamendri** [comment]
looking good!

Once you resolve the conflicts, I will approve, thanks!

**Comment by Easybuoy** [comment]
> thank you @iamcristos i just did it.

Can you resolve the conflict @mbayefaye

**Comment by mbayefaye** [comment]
Guys i 've resolved the conflict.

**Pull request merged**
