### PR TITLE
Re-style Footer

### PR DESCRIPTION
**Pull request by Easybuoy**
#### What does this PR do?
- Re-style Footer

#### Description of Task to be completed?
- Re-style Footer & add newsletter functionality

#### How should this be manually tested?
- Check the footer of the application

#### What are the relevant Trello Card stories? [ Trello Card Item ](https://trello.com/b/8x3mo2V5/say-their-names-web)
- https://trello.com/c/BIReYJTc/64-possibly-remove-email-from-footer

#### Pull Request Type (check one)
- [x] Feature
- [ ] Bug Fixes
- [x] Chore

#### Developer Checklist
- [x] New code has been scanned for ESlint issues
- [x] I have tested my code locally
- [x] I made sure that there are no other pull requests that solve for this issue
- [x] My code follows the same structure within the guidelines

### CODE REVIEW

**Comment by kouamendri** [comment]
@Easybuoy Can you remove the settings link as well?

**Comment by Easybuoy** [comment]
> @Easybuoy Can you remove the settings link as well?

Done @kouamendri

**Comment by YourMobileGeek** [comment]
Just circling back on this, so @Bedrock02 & @DanFerrer can approve.

**Comment by Easybuoy** [comment]
> Just circling back on this, so @Bedrock02 & @DanFerrer can approve.

Anyone can approve if you think it's good to go, we just need at least 2 code reviews on every PR

**Comment by kouamendri** [comment]
could you resolve the conflicts?

**Pull request merged**
