### PR TITLE
feat:about

### PR DESCRIPTION
**Pull request by Utieee**
#### What does this PR do?
--Add the About page

#### Description of Task to be completed?
-

#### How should this be manually tested?
--npm start

#### What are the relevant Trello Card stories? [ Trello Card Item ](https://trello.com/b/8x3mo2V5/say-their-names-web)
-https://trello.com/c/zt31Unan/40-about-page

#### Pull Request Type (check one)
- [x] Feature
- [ ] Bug Fixes
- [ ] Chore

#### Developer Checklist
- [x] New code has been scanned for ESlint issues
- [x] I have tested my code locally
- [x] I made sure that there are no other pull requests that solve for this issue
- [x] My code follows the same structure within the guidelines

### CODE REVIEW

**Comment by kouamendri** [comment]
`Failed to compile.

./src/pages/about/About.js
  Line 12:1:  This line has a length of 343. Maximum allowed is 200  max-len

Search for the keywords to learn more about each error.`

@Utieee @Easybuoy am i the only one getting this error?

**Comment by Easybuoy** [comment]
> `Failed to compile.
> 
> ./src/pages/about/About.js
> Line 12:1: This line has a length of 343. Maximum allowed is 200 max-len
> 
> Search for the keywords to learn more about each error.`
> 
> @Utieee @Easybuoy am i the only one getting this error?
> 
> Looks like the new eslint rule is blocking it from compiling on my end.
> 
> Once that is resolved. I will approve and merge in.

Yeah, the lines just need to be broken to separate lines. Unfortunately, `eslint --fix` doesn't fix it automatically

**Comment by Easybuoy** [comment]
@kouamendri Fixed, check again

**Comment by kouamendri** [comment]
@Easybuoy could you take a look at this? [https://ibb.co/sV4Qbt7](url)

**Pull request merged**
